### ISSUE TITLE
Resample CT volumes to a unified voxel size of 1.0×1.0×3.0 mm3.

### ISSUE THREAD

**Issue by DDxk369** [YtongXie/UniMiSS-code#2]
Thank you for your contribution and I can't wait to try running this code, but I don't know how to **Resample CT volumes to a unified voxel size of 1.0×1.0× 3.0mm3**. Could you tell me what I should do?

**Comment by YtongXie** [comment]
You can follow this code for resampling.
https://github.com/jianpengz/DoDNet/blob/main/dataset/re_spacing.py

Thanks~
