### ISSUE TITLE
Finetune for 2D classification task

### ISSUE THREAD

**Issue by liyi01827** [YtongXie/UniMiSS-code#3]
Hi, This is an interesting work. Can you also provide the code for fine-tune on 2d image classification tasks? The hyper-params are missing for these downstream 2d tasks. Thanks a lot.

**Comment by liyi01827** [comment]
For "fine-tune" in the paper, does it mean freeze the encoder and only train a linear classifier or train them together?

**Comment by YtongXie** [comment]
> ean freeze the encoder and only train a linear classifier or train them

"fine-tune" means training both encoder and linear classifier together

**Comment by YtongXie** [comment]
> Hi, This is an interesting work. Can you also provide the code for fine-tune on 2d image classification tasks? The hyper-params are missing for these downstream 2d tasks. Thanks a lot.

We have provided the code for fine-tuning 3d classification task and will provide the code for fine-tuning 2d tasks later.

**Comment by coolboy497** [comment]
Hi, @YtongXie，Your work catch my eyes, when will you provide the code for fine-tuning 2d tasks ? I very interested to see it, thank  you very much

**Comment by YtongXie** [comment]
We have provided the code for fine-tuning 2d tasks. 
https://github.com/YtongXie/UniMiSS-code/tree/main/UniMiSSPlus/Downstream/2D
