### ISSUE TITLE
UniMiSS+ availability

### ISSUE THREAD

**Issue by jiang131072** [YtongXie/UniMiSS-code#5]
When will code and weights of UniMiSS+ be available?

**Comment by YtongXie** [comment]
Thanks for your asking. We will release them in two weeks.

**Comment by argman** [comment]
four weeks passed~

**Comment by YtongXie** [comment]
Thanks for your attention. Our server was under maintenance recently and has just been fixed. We will update the code ASAP.

**Comment by YtongXie** [comment]
Hi all, we have released UniMiSS+ pre-training code and weights and UniMiSS+ fine-tuning code. Thanks for your attention again.

**Comment by argman** [comment]
> Hi all, we have released UniMiSS+ pre-training code and weights and UniMiSS+ fine-tuning code. Thanks for your attention again.

whats the main difference between UniMiss+ and UniMiss ? as i cannot find a pdf version of the paper

**Comment by YtongXie** [comment]
> > Hi all, we have released UniMiSS+ pre-training code and weights and UniMiSS+ fine-tuning code. Thanks for your attention again.
> 
> whats the main difference between UniMiss+ and UniMiss ? as i cannot find a pdf version of the paper

Please see these links
https://link.springer.com/chapter/10.1007/978-3-031-19803-8_33
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10617802
